name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  swiftlint:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: SwiftLint
      run: swiftlint
      
  swiftformat:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: SwiftFormat
      run: swiftformat --lint --verbose .

  tests:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build and Test
      run: swift build && swift test
