name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  swiftlint:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: SwiftLint
      run: swiftlint

  tests:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build and Test
      run: swift test --enable-code-coverage
      
    - name: Code coverage
      run: xcrun llvm-cov export -format="lcov" .build/debug/macos-mac-addressPackageTests.xctest -instr-profile .build/debug/codecov/default.profdata > unit.lcov
      continue-on-error: true
      
    - uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
